import { Room } from '../types/room';
import { Booking } from '../types/booking';

export const INITIAL_ROOMS: Room[] = [
  {
    id: 'room-1',
    name: 'Phòng Lab A3-101',
    building: 'Tòa nhà A3',
    floor: 'Tầng 1 - Khu A3',
    capacity: 30,
    status: 'Available',
    photoUrl: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng thực hành máy tính cấu hình cao trang bị máy chiếu 4K, bảng trắng lớn và màn hình phụ. Rất phù hợp cho nhóm học lập trình và workshop công nghệ.',
    amenities: ['Wi-Fi tốc độ cao', 'Bảng viết dạ', 'Máy chiếu 4K', 'Ổ cắm điện đa năng', 'Điều hòa không khí', 'Màn hình kép'],
    rating: 4.9,
    noiseLevel: 'Thảo luận nhóm',
  },
  {
    id: 'room-2',
    name: 'Khu tự học B - Thư viện',
    building: 'Thư viện Trung tâm',
    floor: 'Tầng 2 - Cánh Đông',
    capacity: 50,
    status: 'Occupied',
    photoUrl: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&auto=format&fit=crop&q=80',
    description: 'Không gian tự học rộng rãi với bàn ghế công thái học, ánh sáng tự nhiên và tường tiêu âm. Không gian lý tưởng cho ôn thi tập trung cao độ.',
    amenities: ['Wi-Fi tốc độ cao', 'Ổ cắm điện đa năng', 'Điều hòa không khí', 'Phòng cách âm'],
    rating: 4.8,
    noiseLevel: 'Yên tĩnh tuyệt đối',
  },
  {
    id: 'room-3',
    name: 'Phòng Lab 402 Tech',
    building: 'Khu Công nghệ',
    floor: 'Tầng 4',
    capacity: 24,
    status: 'Available',
    photoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng lab chuyên đề với bàn ghế lắp ghép linh hoạt, thiết bị họp hội nghị trực tuyến và internet cáp quang tốc độ cao.',
    amenities: ['Wi-Fi tốc độ cao', 'Thiết bị họp trực tuyến', 'Máy chiếu 4K', 'Bảng viết dạ', 'Điều hòa không khí'],
    rating: 4.7,
    noiseLevel: 'Thảo luận nhóm',
  },
  {
    id: 'room-4',
    name: 'Khoang Học Nhóm C1 (Pod)',
    building: 'Thư viện Trung tâm',
    floor: 'Tầng 3',
    capacity: 6,
    status: 'Available',
    photoUrl: 'https://images.unsplash.com/photo-1524178232363-1fb2b075b655?w=800&auto=format&fit=crop&q=80',
    description: 'Khoang cách âm riêng biệt dành cho nhóm học tập từ 4-6 người. Có bảng trắng riêng, cổng sạc nhanh đa năng và đèn chống mỏi mắt.',
    amenities: ['Wi-Fi tốc độ cao', 'Bảng viết dạ', 'Phòng cách âm', 'Ổ cắm điện đa năng', 'Điều hòa không khí'],
    rating: 4.9,
    noiseLevel: 'Yên tĩnh',
  },
  {
    id: 'room-5',
    name: 'Studio Khởi Nghiệp Sáng Tạo',
    building: 'Không gian Sáng tạo',
    floor: 'Tầng Trệt',
    capacity: 40,
    status: 'Available',
    photoUrl: 'https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&auto=format&fit=crop&q=80',
    description: 'Thiết kế mở hiện đại với các bảng tương tác thông minh, góc thuyết trình sân khấu nhỏ và khu vực brainstorm nhóm năng động.',
    amenities: ['Wi-Fi tốc độ cao', 'Bảng viết dạ', 'Máy chiếu 4K', 'Thiết bị họp trực tuyến', 'Ổ cắm điện đa năng'],
    rating: 4.9,
    noiseLevel: 'Thảo luận nhóm',
  },
  {
    id: 'room-6',
    name: 'Phòng Hội Thảo Vật Lý 201',
    building: 'Giảng đường Khoa học',
    floor: 'Tầng 2',
    capacity: 18,
    status: 'Occupied',
    photoUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng học dạng bậc thang chuyên dụng cho báo cáo tiểu luận khoa học, bảo vệ đồ án chuyên ngành và giải bài tập nhóm.',
    amenities: ['Bảng viết dạ', 'Máy chiếu 4K', 'Ổ cắm điện đa năng', 'Điều hòa không khí'],
    rating: 4.6,
    noiseLevel: 'Yên tĩnh',
  },
  {
    id: 'room-7',
    name: 'Xưởng Chế Tác Robot & IoT',
    building: 'Tòa nhà A3',
    floor: 'Tầng Hầm B2',
    capacity: 35,
    status: 'Available',
    photoUrl: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng kỹ thuật trang bị bàn làm việc chống tĩnh điện, máy in 3D mẫu, bộ cấp nguồn thí nghiệm và máy đo chuyên dụng.',
    amenities: ['Wi-Fi tốc độ cao', 'Ổ cắm điện đa năng', 'Điều hòa không khí', 'Màn hình kép', 'Bảng viết dạ'],
    rating: 4.8,
    noiseLevel: 'Thảo luận nhóm',
  },
  {
    id: 'room-8',
    name: 'Phòng Họp Ban Cán Sự 3B',
    building: 'Khu Công nghệ',
    floor: 'Tầng 3',
    capacity: 16,
    status: 'Available',
    photoUrl: 'https://images.unsplash.com/photo-1431540015161-0bf8663c16ba?w=800&auto=format&fit=crop&q=80',
    description: 'Phòng họp tiêu chuẩn cao cấp với màn hình tương tác 85 inch, ghế da êm ái và hệ thống âm thanh định hướng rõ nét.',
    amenities: ['Wi-Fi tốc độ cao', 'Thiết bị họp trực tuyến', 'Máy chiếu 4K', 'Phòng cách âm', 'Điều hòa không khí'],
    rating: 4.9,
    noiseLevel: 'Yên tĩnh',
  },
];

export const STANDARD_TIME_SLOTS = [
  { id: '08:00-09:30', startTime: '08:00', endTime: '09:30' },
  { id: '09:30-11:00', startTime: '09:30', endTime: '11:00' },
  { id: '11:00-12:30', startTime: '11:00', endTime: '12:30' },
  { id: '13:00-14:30', startTime: '13:00', endTime: '14:30' },
  { id: '14:30-16:00', startTime: '14:30', endTime: '16:00' },
  { id: '16:00-17:30', startTime: '16:00', endTime: '17:30' },
  { id: '17:30-19:00', startTime: '17:30', endTime: '19:00' },
  { id: '19:00-20:30', startTime: '19:00', endTime: '20:30' },
];

export const getTodayDateString = (daysOffset: number = 0): string => {
  const d = new Date();
  d.setDate(d.getDate() + daysOffset);
  const year = d.getFullYear();
  const month = String(d.getMonth() + 1).padStart(2, '0');
  const day = String(d.getDate()).padStart(2, '0');
  return `${year}-${month}-${day}`;
};

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk-101',
    roomId: 'room-2',
    roomName: 'Khu tự học B - Thư viện',
    roomPhoto: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=800&auto=format&fit=crop&q=80',
    building: 'Thư viện Trung tâm',
    date: getTodayDateString(0),
    slotId: '09:30-11:00',
    startTime: '09:30',
    endTime: '11:00',
    studentId: 'STU-2024-88',
    studentName: 'Alex Nguyễn',
    purpose: 'Học tập trung ôn thi môn Cấu trúc dữ liệu & Giải thuật',
    status: 'Upcoming',
    createdAt: new Date().toISOString(),
    checkInCode: 'SRB-8821',
  },
  {
    id: 'bk-102',
    roomId: 'room-6',
    roomName: 'Phòng Hội Thảo Vật Lý 201',
    roomPhoto: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
    building: 'Giảng đường Khoa học',
    date: getTodayDateString(0),
    slotId: '13:00-14:30',
    startTime: '13:00',
    endTime: '14:30',
    studentId: 'STU-2024-99',
    studentName: 'Sarah Jenkins',
    purpose: 'Báo cáo tiến độ đồ án Vật lý bán dẫn',
    status: 'Upcoming',
    createdAt: new Date().toISOString(),
    checkInCode: 'SRB-4319',
  },
  {
    id: 'bk-100',
    roomId: 'room-1',
    roomName: 'Phòng Lab A3-101',
    roomPhoto: 'https://images.unsplash.com/photo-1517502884422-41eaead166d4?w=800&auto=format&fit=crop&q=80',
    building: 'Tòa nhà A3',
    date: getTodayDateString(-1),
    slotId: '14:30-16:00',
    startTime: '14:30',
    endTime: '16:00',
    studentId: 'STU-2024-88',
    studentName: 'Alex Nguyễn',
    purpose: 'Họp nhóm Sprint Review dự án React Native',
    status: 'Completed',
    createdAt: new Date().toISOString(),
    checkInCode: 'SRB-1192',
  },
];
